### ISSUE TITLE
Channel name before (128) and after (105) preprocess

### ISSUE THREAD

**Issue by MichaelMaiii** [NeuSpeech/EEG-To-Text#11]
Hi, where can I find channel names before (128) and after (105) preprocess, I loaded the dataset and found nothing (only hdf5 object reference, which is none) in it, can you provide this information for me? Thanks a lot.
![image](https://github.com/user-attachments/assets/3699d0e7-97e2-40d4-b1d0-033781ddfb75)

**Comment by NeuSpeech** [comment]
if the original file does not contain channels names, I cannot help either.

**Comment by NeuSpeech** [comment]
but I guess there is some information in the dataset paper.
