### ISSUE TITLE
Pretrained weights for Step 1 not found

### ISSUE THREAD

**Issue by Dark-knight-02** [NeuSpeech/EEG-To-Text#5]
I was trying to reproduce the paper and the pretrained weights for step 1 'path_to_step_1_checkpoint.pt' was not in the GitHub. Could you please upload the weights?

**Comment by NeuSpeech** [comment]
I think you don't need pretrained weights. It only trains the step2

**Comment by Dark-knight-02** [comment]
Yes while I was trying to regenerate the paper on default settings the BeLu-1 score that I am getting is around 0.24 and not that mentioned in the results of the paper. Is there any suggestions to improve the score or on the exact configuration to receive the best result?

**Comment by Dark-knight-02** [comment]
If possible can you please share the path_to_step_1_checkpoint.pt file?

**Comment by NeuSpeech** [comment]
there is no step_1_checkpoint.pt file. we updated code in main branch to reproduce the results in paper. please check out.
