### ISSUE TITLE
Problem of the teacher forcing result when train_input=noise

### ISSUE THREAD

**Issue by boom-R123** [NeuSpeech/EEG-To-Text#9]
Hi, thanks for your code.
When set train_input to noise, I find that all the predicted results with teacher forcing are \<s\> during inference. It seems that the training process crashed.
![image](https://github.com/NeuSpeech/EEG-To-Text/assets/63643964/969f57e0-062a-4323-a4fe-08d6e0569074)
After trying, I found that changing the random seed can improve this situation. The random seed has a great impact on the training process. Some random seeds will cause training failure.

**Comment by girlsending0** [comment]
Thank you for find problem and resolved it!
